name: Pull Request Comment Trigger
'on':
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  pull_request_comment_trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: get the repo
      - name: get node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm i
        run: npm i
      - name: try it out
        run: ./pull-request-comment-trigger.js
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          INPUT_TRIGGER: '@build/android'