name: Pull Request Comment Trigger
'on':
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  pull_request_comment_trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/pull-request-comment-trigger@1.0.0
        id: check
        with:
          trigger: '#build/android'
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@0.3.0
        if: steps.check.outputs.triggered == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const core = require('@actions/core')
            let ref = process.env.GITHUB_REF;
            if (context.eventName === 'issue_comment') {
              const pr = context.payload.issue.pull_request;
              if (!pr) {
                core.setFailed('Not a pull request issue comment')
                process.exit(1)
              }
              ref = 'refs/pull/' + context.payload.issue.number + '/merge'
              console.log(JSON.stringify(pr))
              // if (!pr.merge_commit_sha) {
              //   core.setFailed('Pull request is not mergeable!')
              //   process.exit(1)
              // }
              // ref = pr.merge_commit_sha
            }
            core.exportVariable(
              'PULL_REQUEST_REF',
              ref
            )
      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'
        name: get the repo
        with:
          ref: ${{ env.PULL_REQUEST_REF }}
      - run: echo 'Ok folks, it is great'
      - run: git rev-parse HEAD
      - name: Report failure
        if: failure() && steps.check.outputs.triggered == 'true'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: 'oh no it failed'})